name: AutoPushNews

on:
  schedule:
    - cron: '*/30 * * * *'
  workflow_dispatch:

env:
  TZ: Asia/Kuala_Lumpur

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - run: pip install -r requirements.txt
      - run: python push_cn_news_to_telegram.py
        env:
          TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
          TG_CHAT_ID: ${{ secrets.TG_CHAT_ID }}
